steps:
  #Execute SnarCloud Scan
  - name: maven:3-eclipse-temurin-17
    entrypoint: mvn
    args:
      [
        "verify",
        "sonar:sonar",
        "-Dsonar.host.url=https://sonarcloud.io",
        "-Dsonar.organization=gcpdevsecopsscan",
        "-Dsonar.projectkey=gcpprojectkey",
        "-Dsonar.login=15d005650ee8ec6a59f4803a50b7f50da811d962",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
